PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX formats: <http://www.w3.org/ns/formats/>
PREFIX : <http://www.example.org/vocals/examples>
PREFIX v: <https://w3id.org/rsp/vocals#>
PREFIX vsd: <https://w3id.org/rsp/vocals-sd#>
PREFIX vprov: <https://w3id.org/rsp/vocals-prov#>

###############################################################################
# Available Streams
###############################################################################
SELECT ?s
WHERE {
  ?s a v:RDFStream .
}
###############################################################################
# Available Endpoints 
###############################################################################
SELECT ?s ?ep
WHERE {
  ?s a v:RDFStream ; v:hasEndpoint ?ep .
}
###############################################################################
# Available Stream Descriptor
###############################################################################
SELECT ?s ?sd
WHERE {
  ?sd a v:StreamDescriptor ; dcat:dataset ?s .
}
###############################################################################
# Stream available partitions 
###############################################################################
SELECT ?s ?p
WHERE {
  ?s v:hasPartition ?p .
}
###############################################################################
# Stream available for a RDF Streaming service 
###############################################################################
SELECT ?s ?sv
WHERE {
  ?sv vsd:registeredStream ?s .
}
###############################################################################
# Available streams registered by a processing services 
###############################################################################
SELECT ?s ?sv
WHERE {
  ?s vsd:registeredBy ?sv .
}
###############################################################################
# Available streams published by a publishing services 
###############################################################################
SELECT ?s ?sv
WHERE {
  ?s vsd:publishedBy ?sv .
}
###############################################################################
# Available streams described by a catalog services 
###############################################################################
SELECT ?s ?sv
WHERE {
  ?s vsd:describedBy ?sv .
}
###############################################################################
# The features of RSService
###############################################################################
SELECT ?sv ?sf
WHERE {
  ?sv vsd:hasFeature ?sf .
  FILTER (?sv = :Triplewave1)
}
###############################################################################
# Registered Task on RSService
###############################################################################
SELECT ?s ?t
WHERE {
  ?sv vsd:registeredTask ?t .
  FILTER (?sv = :Engine1)
}
###############################################################################
# The services having a filtering feature
###############################################################################
SELECT ?sv
WHERE {
  ?sv vsd:hasFeature ?sf .
  FILTER (?sf = vsd:filtering)
}
###############################################################################
# List of window generated by RSService
###############################################################################
SELECT ?w ?si ?ei
WHERE {
  ?w a vsd:Window ; vsd:startedAt ?si ; vsd:endedAt ?ei .
  FILTER (?sv = :Engine1)
}
###############################################################################
# List of RSService with RSP Endpoint
###############################################################################
SELECT ?sv ?ep
WHERE {
  ?sv a vsd:RSService ; vsd:rspEndpoint ?ep.
}
